# helpful link:
#https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages


matrix:
  include:

    - language: cpp
      compiler: gcc
      # (Optional? update to a relatively recent linux distro)
      dist: xenial
      install:
        - sudo apt-get install -qq cppcheck
      script:
        - source for_debugging_and_profiling/setup_gcc_linux_dbg.sh
        - make clean
        - make
        - cd tests
        - ../bin/filter_mrc/filter_mrc -i test_image_membrane.rec -mask-rect 1 14 2 14 2 14 -out test_image_fluct.rec -fluct 60
        #- cppcheck --quiet --error-exitcode=1   #(Am I invoking cppcheck correctly?)
        - ../bin/filter_mrc/filter_mrc -w 19.2 -w 19.2 -i test_image_membrane.rec -out test_image_membrane_planar_55_tv_4_4_clust_1e+09_0.707_0.707_0.707_0.707.rec -planar 55 -planar-tv 4 -planar-tv-angle-exponent 4 -connect-vector-saliency 0.707 -connect-vector-neighbor 0.707 -connect-tensor-saliency 0.707 -connect-tensor-neighbor 0.707 -connect-saliency 1e+09 -planar-normals-file test_image_membrane_planar_55_tv_4_4_clust_1e+09_0.707_0.707_0.707_0.707.obj -select-cluster 1
        #- cppcheck --quiet --error-exitcode=1   #(Am I invoking cppcheck correctly?)
        - cd ../

    - language: bash
      before_script:
        # Install "shunit2"
        - git clone https://github.com/kward/shunit2 shunit2
      script:
        - bash tests/test_fluctuation_filter.sh
        - bash tests/test_membrane_detection.sh

