dist: xenial
# (older versions of ubuntu lack a modern gcc compiler.)
language: cpp, bash
compiler: gcc

# Download the version of gcc that we will need to compile the code.
#
#before_install:
#    Perhaps this is no longer necessary:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq gcc-7 g++-7
#  - alias gcc='gcc-7'
#
# NOTE: There's an alternative way to do this using the "matrix" keyword.
#       https://docs.travis-ci.com/user/languages/cpp/


#install:
#  I'll worry about this later:
#  - sudo apt-get install -qq cppcheck


before_script:

  # Install "shunit2"

  # Note sure where to find the most dependable source for "shunit2". Try this:

  - git clone https://github.com/kward/shunit2 shunit2

script:
  - source for_debugging_and_profiling/setup_gcc_linux_dbg.sh
  - make clean
  - make
  - cd tests
  - bin/filter_mrc/filter_mrc -i test_image_membrane.rec -mask-rect 1 14 2 14 2 14 -out test_image_fluct.rec -fluct 60
  #- cppcheck --quiet --error-exitcode=1   #(Am I invoking cppcheck correctly?)
  - bin/filter_mrc/filter_mrc -w 19.2 -w 19.2 -i test_image_membrane.rec -out test_image_membrane_planar_55_tv_4_4_clust_1e+09_0.707_0.707_0.707_0.707.rec -planar 55 -planar-tv 4 -planar-tv-angle-exponent 4 -connect-vector-saliency 0.707 -connect-vector-neighbor 0.707 -connect-tensor-saliency 0.707 -connect-tensor-neighbor 0.707 -connect-saliency 1e+09 -planar-normals-file test_image_membrane_planar_55_tv_4_4_clust_1e+09_0.707_0.707_0.707_0.707.obj -select-cluster 1
  #- cppcheck --quiet --error-exitcode=1   #(Am I invoking cppcheck correctly?)
  - cd ../
  # Optional:
  #   Check the the output files created by the commands above are correct.
  #- bash tests/test_fluctuation_filter.sh
  #- bash tests/test_membrane_detection.sh
  # (This may require adding the line "language: c++, bash" to this file.)

